/* 弃用原型：三个结构不同的候选布局，通过 ?variant=A/B/C 比较。全部数据与操作仅在内存中。 */
const $ = s => document.querySelector(s);
const esc = x => String(x ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states = {completed:'完成',failed:'失败',terminated:'终止',running:'运行中',waiting:'限速等待',pending:'待执行',not_executed:'未执行',unknown:'中断 · 结果未知'};
const badge = (state,text) => `<span class="badge ${state}">${esc(text || states[state])}</span>`;
const tools = [{name:'maps_text_search',description:'按城市和关键词搜索地点',input_schema:{type:'object',properties:{keywords:{type:'string'},city:{type:'string'},citylimit:{type:'string'}}}},{name:'maps_direction_walking',description:'查询步行交通路线',input_schema:{type:'object',properties:{origin:{type:'string'},destination:{type:'string'}}}}];
let serial=0;
function makeTurn(input,mode='normal') {
  const id=`turn-${++serial}`, reqs=[], events=[];
  const modelPayload={model:'旅行模型（模拟）',system:'你是旅行助手。旅行事实以工具返回为依据；缺失内容明确标为待核实。此处为模拟系统提示。',messages:[{role:'user',content:input}],tools,max_tokens:4096};
  const response=(n,c,stop='tool_use')=>({id:`mock-message-${id}-${n}`,model:'旅行模型（模拟）',role:'assistant',content:c,stop_reason:stop,usage:{input_tokens:1200+n*160,output_tokens:n===1?210:340,cache_read_input_tokens:0}});
  const r1={id:`${id}-r1`,type:'model',name:'模型请求 1',state:'completed',at:0,duration:1200,input:structuredClone(modelPayload),output:response(1,[{type:'tool_use',id:`toolu-${id}-1`,name:'maps_text_search',input:{keywords:'西湖',city:'杭州',citylimit:'true'}},{type:'tool_use',id:`toolu-${id}-2`,name:'maps_text_search',input:{keywords:'灵隐寺',city:'杭州',citylimit:'true'}}]),usage:{input_tokens:1360,output_tokens:210,cache_read_input_tokens:0},children:[]};
  reqs.push(r1);events.push(r1);
  const t1={id:`${id}-t1`,request_id:r1.id,type:'tool',name:'maps_text_search',summary:'西湖 · 杭州',state:'completed',at:1.2,duration:710,wait:0,call:708,input:{keywords:'西湖',city:'杭州',citylimit:'true'},output:{is_error:false,content:[{type:'text',text:'模拟结果：杭州西湖，浙江省杭州市西湖区'}],structured_content:{pois:Array.from({length:16},(_,i)=>({id:`mock-poi-${i+1}`,name:i===0?'西湖':`模拟候选地点 ${i+1}`,address:'浙江省杭州市西湖区（模拟）',location:'120.15,30.24',description:'这是用于长 JSON 阅读的模拟字段；地址与坐标不用于真实出行。'.repeat(3)}))}},children:[]};
  t1.backfill={type:'tool_result',tool_use_id:`toolu-${id}-1`,content:JSON.stringify(t1.output),is_error:false};
  const t2={id:`${id}-t2`,request_id:r1.id,type:'tool',name:'maps_text_search',summary:'灵隐寺 · 杭州',state:'completed',at:1.91,duration:950,wait:120,call:828,input:{keywords:'灵隐寺',city:'杭州',citylimit:'true'},output:{is_error:false,content:[{type:'text',text:'模拟结果：灵隐寺，浙江省杭州市西湖区法云弄'}]},children:[]};
  t2.backfill={type:'tool_result',tool_use_id:`toolu-${id}-2`,content:JSON.stringify(t2.output),is_error:false};
  r1.children.push(t1,t2);events.push(t1,t2);
  if(mode==='partial') {t2.state='failed';t2.duration=30120;t2.call=30000;t2.output=null;t2.error={stage:'tool_call',category:'timeout',message:'工具请求超过 30 秒，未取得已解析服务结果（模拟）'};t2.backfill={type:'tool_result',tool_use_id:`toolu-${id}-2`,content:t2.error.message,is_error:true};}
  if(mode==='budget'){t2.state='not_executed';t2.duration=2;t2.call=null;t2.wait=0;t2.output=null;t2.error={stage:'application',category:'tool_budget',message:'本轮工具调用预算耗尽，未进入 SDK 调用（模拟预算缩小）'};t2.backfill={type:'tool_result',tool_use_id:`toolu-${id}-2`,content:t2.error.message,is_error:true};}
  if(mode==='running'){t2.state='running';t2.duration=null;t2.call=null;t2.output=null;t2.backfill=null;}
  if(mode==='interrupted'){t2.state='unknown';t2.duration=null;t2.call=null;t2.output=null;t2.backfill=null;t2.error={stage:'recovery',category:'service_interrupted',message:'服务中断后发现缺失结束记录；远端结果未知，不补造耗时。'};}
  let answer='建议上午游览西湖，下午前往灵隐寺。地点检索已经完成；两地之间的交通路线、门票与当日开放时间仍待核实。\n\n以上是模拟回答，仅用于评估交互，不可作为真实旅行依据。';
  if(mode==='partial')answer='已取得西湖的模拟地点结果。灵隐寺查询超时，地址与后续交通待核实。保留成功信息，本轮正常给出回答。';
  if(mode==='budget')answer='本轮因工具调用预算耗尽而终止。已取得西湖模拟结果；灵隐寺工具调用未执行。此说明由应用生成。';
  if(mode==='interrupted')answer='服务中断，本轮已终止。已保存部分可回看；缺失结束记录的工具结果未知。整个中断轮次不会用于后续模型上下文。';
  if(mode==='running')answer='';
  let state=['budget','interrupted'].includes(mode)?'terminated':mode==='running'?'running':'completed';
  if(!['budget','running','interrupted'].includes(mode)){
    const r2={id:`${id}-r2`,type:'model',name:'模型请求 2',state:mode==='model-fail'?'failed':'completed',at:mode==='partial'?32.03:2.86,duration:1600,input:{...structuredClone(modelPayload),messages:[...modelPayload.messages,{role:'assistant',content:r1.output.content},{role:'user',content:[t1.backfill,t2.backfill]}]},output:response(2,[{type:'text',text:answer}],'end_turn'),usage:{input_tokens:1520,output_tokens:340},children:[]};
    if(mode==='model-fail'){r2.output=null;r2.usage=null;r2.error={stage:'model_request',category:'network',message:'模型服务连接失败（模拟），未取得响应与 usage'};state='failed';answer='模型服务连接失败。本次已查到的模拟地点结果仍保留。此停止说明由应用生成。';}
    reqs.push(r2);events.push(r2);
  }
  const turn={id,type:'turn',name:'对话轮次',input,answer,state,mode,requests:reqs,events,duration:mode==='running'||mode==='interrupted'?null:mode==='partial'?33630:4460,reason:mode==='budget'?'工具调用预算耗尽':mode==='interrupted'?'服务中断':mode==='model-fail'?'模型服务连接失败':null,source:['budget','interrupted','model-fail'].includes(mode)?'application':'model'};
  return turn;
}
let sessions=[
 {id:'normal',title:'杭州两日旅行 · 调整首站',time:'今天 14:10',turns:[makeTurn('在杭州安排两日旅行，清淡不辣，公交优先。'),makeTurn('把第 2 天首站换成灵隐寺，其他条件不变。')]},
 {id:'partial',title:'部分失败 · 地点查询超时',time:'今天 13:55',turns:[makeTurn('查询西湖和灵隐寺，看看怎么安排。','partial')]},
 {id:'budget',title:'预算终止 · 未执行调用',time:'今天 13:40',turns:[makeTurn('查询两个地点，比较交通。','budget')]},
 {id:'running',title:'运行中 · 三日旅行查询',time:'今天 13:30',turns:[makeTurn('安排三日杭州旅行，每天两个活动。','running')]},
 {id:'saved',title:'历史会话 · 模型服务失败',time:'昨天 18:26 · 模拟保存',turns:[makeTurn('查一下西湖附近的地点。','model-fail')]},
 {id:'interrupted',title:'服务中断 · 结果未知',time:'昨天 17:08 · 模拟保存',turns:[makeTurn('查询杭州旅行地点。','interrupted')]}
];
// “运行中”样例进入时激活；避免未访问的演示场景占用全局名额。
const first=sessions[0].turns[0], second=sessions[0].turns[1];
const previousMessages=[{role:'user',content:first.input},...first.requests.flatMap(r=>[{role:'assistant',content:r.output.content},...(r.children.length?[{role:'user',content:r.children.map(c=>c.backfill)}]:[])])];
second.requests.forEach(r=>r.input.messages=[...structuredClone(previousMessages),...r.input.messages]);
let activeId='normal',view='chat',variant=new URLSearchParams(location.search).get('variant')||'A',selection=null,openTurns=new Set(),openRequests=new Set(),drafts={},busyId=null,stopping=false,query='',scope='all',wrap=true,jsonOpen=new Set(),dialogAction=null,pendingTimer=null,hasNew=false;
if(!['A','B','C'].includes(variant))variant='A';
const current=()=>sessions.find(s=>s.id===activeId);
const allEvents=()=>current()?.turns.flatMap(t=>[t,...t.events])||[];
function initExpansion(){openTurns=new Set();openRequests=new Set();const t=current()?.turns.at(-1);if(t){openTurns.add(t.id);t.requests.forEach(r=>openRequests.add(r.id));}selection=null;jsonOpen.clear();query='';$('#search').value='';}
initExpansion();
function overall(s){const t=s.turns.at(-1);return t?badge(t.state,t.mode==='partial'?'完成 · 含工具错误':states[t.state]):'';}
function renderShell(){const s=current();$('#title').textContent=s?.title||'新的旅行，从这里开始';$('#sessions').innerHTML=sessions.map(x=>`<button class="session ${x.id===activeId?'active':''}" data-session="${x.id}"><strong>${esc(x.title)}</strong><small><span>${esc(x.time)}</span>${overall(x)}</small></button>`).join('');$('#count').textContent=s?.turns.length||0;$('#delete').disabled=!s||busyId===activeId;$('#chat').hidden=view!=='chat';$('#trace').hidden=view!=='trace';$('#chat-tab').classList.toggle('active',view==='chat');$('#trace-tab').classList.toggle('active',view==='trace');$('#tab-note').textContent='助手会话 → 对话轮次 → 模型请求 → 工具调用';$('#variant-name').textContent={A:'A · 事件表 + 右侧详情',B:'B · 轮次导航 + 行内详情',C:'C · 时间线 + 下方检查器'}[variant];
  $('#global-status').innerHTML=busyId?`<div class="notice"><span>${stopping?'正在停止 · 等当前调用返回后结束':`正在运行：${esc(sessions.find(x=>x.id===busyId)?.title)}`}。可以浏览和编辑草稿，暂不能再次发送。</span><button data-action="finish" ${stopping?'disabled':''}>模拟当前调用返回</button><button data-action="stop" ${stopping?'disabled':''}>停止本轮</button></div>`:'';
  $('#send').disabled=!!busyId;$('#send-help').textContent=busyId?'另一轮正在运行或停止，暂不能发送；切换不会停止后台轮次。':'Enter 发送 · Shift + Enter 换行 · 回答为模拟文本';$('#draft').value=drafts[activeId]||'';renderChat();renderTrace();}
function renderChat(){const s=current();$('#messages').innerHTML=s?.turns.length?s.turns.map((t,i)=>`<article class="message user"><div class="message-label">你 · 第 ${i+1} 轮</div>${esc(t.input)}</article><article class="message assistant"><div class="message-label"><span>旅行助手 ${badge(t.state,t.mode==='partial'?'完成 · 含工具错误':states[t.state])}</span><button data-trace-turn="${t.id}">查看本轮轨迹 ↗</button></div>${esc(t.answer||'正在查询地点… 回答将在本轮结束后展示。')}<div class="answer-source">${t.source==='application'?'应用停止说明':'模型回答'}${t.mode==='interrupted'?' · 本轮不进入后续模型上下文':''}</div></article>`).join(''):'<div class="empty"><h2>把旅行想法说给助手</h2><p>查询地点、比较交通、安排旅行行程。<br>发送后可在执行轨迹中查看每次模型请求和工具调用。</p></div>';}
function stats(t){const known=t.requests.filter(r=>r.usage);const input=known.reduce((n,r)=>n+r.usage.input_tokens,0);const output=known.reduce((n,r)=>n+r.usage.output_tokens,0);return `<div class="stats"><span>总耗时 ${t.duration===null?(t.state==='running'?'尚未结束':'未采集完成耗时'):(t.duration/1000).toFixed(2)+' s'}</span><span>${t.requests.length} 次模型请求 · ${t.events.filter(e=>e.type==='tool').length} 个工具调用</span><span>已知输入 ${input.toLocaleString()} token / 输出 ${output.toLocaleString()} token · 覆盖 ${known.length}/${t.requests.length}</span><span>缓存读取 0 · 覆盖 1/${t.requests.length}</span></div>`;}
function timeline(t){return `<div class="timeline" aria-label="第 ${current().turns.indexOf(t)+1} 轮时间线">${t.events.map(e=>`<button class="${e.type} ${selection===e.id?'selected':''}" data-event="${e.id}" title="${esc(e.name)}">+${e.at.toFixed(2)}s ${e.type==='model'?'模型':'工具'} ${states[e.state]}</button>`).join('<span aria-hidden="true">—</span>')}</div>`;}
function duration(e){return e.type==='tool'&&e.state==='not_executed'?'—（未调用）':e.duration===null?(e.state==='unknown'?'未知':'尚未结束'):(e.duration/1000).toFixed(2)+' s';}
function eventRow(e){return `<tr class="event-row ${e.type==='tool'?'tool-row':''} ${selection===e.id?'selected':''}" id="row-${e.id}"><td>+${e.at.toFixed(2)}s</td><td>${e.type==='model'&&e.children.length?`<button class="tree-toggle" data-request="${e.id}" aria-expanded="${openRequests.has(e.id)}" aria-label="展开或收起 ${e.name}" aria-controls="children-${e.id}">${openRequests.has(e.id)?'▾':'▸'}</button>`:''}<button data-event="${e.id}">${esc(e.name)}</button><span class="row-summary">${esc(e.summary||e.error?.message||e.output?.stop_reason||'')}</span></td><td>${badge(e.state)}</td><td>${duration(e)}</td></tr>${variant==='B'&&selection===e.id?`<tr class="inline-detail"><td colspan="4">${inspector(e)}</td></tr>`:''}`;}
function turnCard(t,i){const open=openTurns.has(t.id);return `<article class="turn-card" id="card-${t.id}"><div class="turn-heading"><button data-turn="${t.id}" aria-expanded="${open}" aria-controls="body-${t.id}"><span>${open?'▾':'▸'}</span><strong>第 ${i+1} 轮</strong>${badge(t.state,t.mode==='partial'?'完成 · 含工具错误':states[t.state])}</button><span class="turn-input">${esc(t.input)}</span></div><div id="body-${t.id}" ${open?'':'hidden'}>${stats(t)}${t.reason?`<div class="status-note">${esc(t.reason)}${t.mode==='interrupted'?' · 本轮不进入后续上下文，缺失调用的结果未知':''}</div>`:''}${timeline(t)}<div class="stats"><button data-event="${t.id}">查看用户输入与最终回答</button></div><table><thead><tr><th>起始</th><th>模型请求 / 工具调用</th><th>状态</th><th>总耗时</th></tr></thead><tbody>${t.requests.map(r=>eventRow(r)+`</tbody><tbody id="children-${r.id}" ${openRequests.has(r.id)?'':'hidden'}>${r.children.map(eventRow).join('')}</tbody><tbody>`).join('')}</tbody></table>${variant==='B'&&selection===t.id?inspector(t):''}</div></article>`;}
function sections(e){if(e.type==='turn')return [{key:'input',name:'完整用户输入',data:e.input},{key:'answer',name:'最终回答',data:{text:e.answer,source:e.source,state:e.state,reason:e.reason,excluded_from_context:e.mode==='interrupted'}}];return [{key:'input',name:e.type==='model'?'完整逻辑请求快照':'完整调用参数',data:e.input},{key:'output',name:e.type==='model'?'完整已解析模型返回':'完整已解析服务结果',data:e.output,missing:e.state==='not_executed'?'未执行，无服务结果':e.state==='unknown'?'中断，结果未知':e.state==='running'?'尚未返回':'未取得已解析响应'},...(e.type==='tool'?[{key:'backfill',name:'实际回填给模型的结果',data:e.backfill,missing:e.state==='unknown'?'未保存，结果未知':'尚未产生'}]:[]),...(e.error?[{key:'error',name:'错误与未执行原因',data:e.error}]:[])];}
function inspector(e){if(!e)return '<aside class="inspector"><div class="empty"><h2>选择一个事件</h2><p>查看完整输入、返回和错误。<br>详情默认折叠，选中后按需展开。</p></div></aside>';const meta=e.type==='tool'?`限速等待：${e.wait/1000} s<br>实际调用：${e.call===null?(e.state==='not_executed'?'—（未调用）':e.state==='unknown'?'未知，缺失结束记录':'尚未结束'):(e.call/1000).toFixed(3)+' s'}<br>工具总耗时：${duration(e)}<br>模型请求关联：${esc(e.request_id)}`:e.type==='model'?`请求耗时：${duration(e)}<br>输入 token：${e.usage?.input_tokens??'未返回'}<br>输出 token：${e.usage?.output_tokens??'未返回'}<br>缓存读取：${e.usage?.cache_read_input_tokens??'未返回'}<br>结束原因：${esc(e.output?.stop_reason||'未返回')}`:'真实用户输入创建一个对话轮次；工具结果不创建新轮次。';return `<aside class="inspector"><div class="inspector-header"><div><h3>${esc(e.name)}</h3><small>${esc(e.id)} · 模拟数据</small></div><button data-action="close-detail" aria-label="关闭详情">×</button></div><div class="inspector-meta">${badge(e.state)}<br>${meta}</div><div class="payloads">${sections(e).map(p=>`<details data-json="${p.key}" ${jsonOpen.has(p.key)?'open':''}><summary>${p.name}</summary>${p.data==null?`<p>${esc(p.missing||'未采集')}</p>`:`<div class="json-tools"><button data-copy="${p.key}">复制完整内容</button><button data-action="wrap">${wrap?'关闭':'开启'}自动换行</button></div><pre class="${wrap?'wrap':''}">${highlight(typeof p.data==='string'?p.data:JSON.stringify(p.data,null,2))}</pre>`}</details>`).join('')}</div></aside>`;}
function highlight(text){if(!query)return esc(text);const parts=String(text).split(new RegExp('('+query.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','ig'));return parts.map((x,i)=>i%2?`<mark>${esc(x)}</mark>`:esc(x)).join('');}
function renderTrace(){const s=current();const e=allEvents().find(e=>e.id===selection);const cards=s?.turns.map(turnCard).join('')||'<div class="empty"><h2>还没有执行轨迹</h2><p>先发送一个旅行问题，生成模拟轮次。</p></div>';$('#trace-body').innerHTML=variant==='A'?`<div class="trace-layout variant-a"><div class="turns">${cards}</div>${inspector(e)}</div>`:variant==='B'?`<div class="trace-layout variant-b"><nav class="rail" aria-label="轮次导航">${s?.turns.map((t,i)=>`<button data-locate-turn="${t.id}">第 ${i+1} 轮 ${badge(t.state)}</button>`).join('')||''}</nav><div class="turns">${cards}</div></div>`:`<div class="trace-layout variant-c"><div class="turns">${cards}</div>${inspector(e)}</div>`;
  $('#trace-body').querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>d.open?jsonOpen.add(d.dataset.json):jsonOpen.delete(d.dataset.json)));
  renderSearch();}
function renderSearch(){const box=$('#search-results');box.hidden=!query;if(!query)return;const hits=[];allEvents().forEach(e=>{if(scope==='summary'){if([e.name,e.summary,e.state,e.reason,e.error?.message,e.type==='turn'?e.input:''].join(' ').toLowerCase().includes(query.toLowerCase()))hits.push({e,key:null,label:'事件摘要'});}else sections(e).forEach(p=>{const text=typeof p.data==='string'?p.data:JSON.stringify(p.data);if(text?.toLowerCase().includes(query.toLowerCase()))hits.push({e,key:p.key,label:p.name});});});box.innerHTML=`<p>${hits.length} 处匹配 · ${scope==='all'?'含折叠的完整输入／输出／错误':'仅摘要'} · 当前助手会话</p>${hits.map(h=>`<button data-hit="${h.e.id}" data-section="${h.key||''}">第 ${current().turns.findIndex(t=>t.id===h.e.id||t.events.some(e=>e.id===h.e.id))+1} 轮 · ${esc(h.e.name)} · ${esc(h.label)}</button>`).join('')}`;}
function selectEvent(id,section=null){selection=id;const t=current().turns.find(t=>t.id===id||t.events.some(e=>e.id===id));if(t){openTurns.add(t.id);t.requests.forEach(r=>{if(r.id===id||r.children.some(c=>c.id===id))openRequests.add(r.id);});}jsonOpen=new Set(section?[section]:[]);renderTrace();const target=document.getElementById(`row-${id}`)||document.getElementById(`card-${id}`);target?.scrollIntoView({block:'nearest'});if(section&&variant!=='B')$('#trace-body .inspector')?.scrollIntoView({block:'nearest'});}
function switchVariant(delta){variant=['A','B','C'][(['A','B','C'].indexOf(variant)+delta+3)%3];const url=new URL(location.href);url.searchParams.set('variant',variant);history.replaceState({},'',url);jsonOpen.clear();renderShell();}
function finish(stopped=false){if(!busyId)return;const s=sessions.find(x=>x.id===busyId),t=s.turns.at(-1),e=t.events.at(-1);e.state='completed';e.duration=950;e.call=828;e.output={is_error:false,content:[{type:'text',text:'当前工具真实模拟返回已保存。'}]};e.backfill={type:'tool_result',tool_use_id:`toolu-${t.id}-2`,content:JSON.stringify(e.output),is_error:false};t.state=stopped?'terminated':'completed';t.mode=stopped?'stopped':'normal';t.reason=stopped?'用户停止':null;t.duration=2860;
  if(stopped){t.source='application';t.answer='本轮已在当前调用返回后停止，已取得的模拟结果保留；没有发起后续模型请求。此说明由应用生成。';}else{t.source='model';t.answer='模拟查询已完成。已取得两处地点结果，交通、门票与营业时间仍待核实。';const r={id:`${t.id}-r2`,type:'model',name:'模型请求 2',state:'completed',at:2.86,duration:1600,input:{...structuredClone(t.requests[0].input),messages:[...t.requests[0].input.messages,{role:'assistant',content:t.requests[0].output.content},{role:'user',content:t.requests[0].children.map(c=>c.backfill)}]},output:{content:[{type:'text',text:t.answer}],stop_reason:'end_turn',usage:{input_tokens:1520,output_tokens:340}},usage:{input_tokens:1520,output_tokens:340},children:[]};t.requests.push(r);t.events.push(r);t.duration=4460;openRequests.add(r.id);}
  busyId=null;stopping=false;s.time='刚刚 · 模拟保存';if(activeId===s.id){renderShell();if(view==='chat')$('#messages').scrollTop=$('#messages').scrollHeight;else if($('#follow').checked)selectEvent(t.events.at(-1).id);else{hasNew=true;$('#trace-body').insertAdjacentHTML('afterbegin','<button class="jump-latest" data-action="latest">有新事件 · 跳到最新</button>');}}else renderShell();}
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.session){activeId=b.dataset.session;if(activeId==='running'&&current().turns.at(-1).state==='running')busyId='running';initExpansion();renderShell();return;}if(b.dataset.tab){view=b.dataset.tab;renderShell();return;}if(b.dataset.traceTurn){view='trace';renderShell();selectEvent(b.dataset.traceTurn);return;}if(b.dataset.turn){const id=b.dataset.turn;openTurns.has(id)?openTurns.delete(id):openTurns.add(id);renderTrace();return;}if(b.dataset.request){const id=b.dataset.request;openRequests.has(id)?openRequests.delete(id):openRequests.add(id);renderTrace();return;}if(b.dataset.event){selectEvent(b.dataset.event);return;}if(b.dataset.locateTurn){openTurns.add(b.dataset.locateTurn);renderTrace();document.getElementById(`card-${b.dataset.locateTurn}`)?.scrollIntoView({block:'start'});return;}if(b.dataset.hit){selectEvent(b.dataset.hit,b.dataset.section||null);return;}if(b.dataset.copy){const e=allEvents().find(x=>x.id===selection),p=sections(e).find(p=>p.key===b.dataset.copy);try{await navigator.clipboard.writeText(typeof p.data==='string'?p.data:JSON.stringify(p.data,null,2));b.textContent='已复制';}catch{b.textContent='请在下方选择文本复制';}return;}
  switch(b.dataset.action){case 'new':activeId='draft';view='chat';initExpansion();renderShell();break;case 'prev':switchVariant(-1);break;case 'next':switchVariant(1);break;case 'expand':current()?.turns.forEach(t=>{openTurns.add(t.id);t.requests.forEach(r=>openRequests.add(r.id));});renderTrace();break;case 'collapse':openTurns.clear();openRequests.clear();selection=null;jsonOpen.clear();renderTrace();break;case 'close-detail':selection=null;renderTrace();break;case 'wrap':wrap=!wrap;renderTrace();break;case 'finish':finish();break;case 'stop':stopping=true;renderShell();pendingTimer=setTimeout(()=>finish(true),1800);break;case 'latest':hasNew=false;selectEvent(current().turns.at(-1).events.at(-1).id);break;case 'rename':case 'delete':if(!current())return;dialogAction=b.dataset.action;$('#dialog-title').textContent=dialogAction==='rename'?'重命名助手会话':'删除这个模拟会话？';$('#dialog-description').textContent=dialogAction==='rename'?'标题仅用于展示，不改变上下文。':'会话及其执行轨迹将从本次原型内存中删除。刷新页面可恢复所有样例。';$('#rename-label').hidden=dialogAction!=='rename';$('#rename-input').value=current().title;$('#manage').showModal();break;}
});
$('#manage').addEventListener('close',()=>{if($('#manage').returnValue!=='confirm')return;if(dialogAction==='rename'&&$('#rename-input').value.trim())current().title=$('#rename-input').value.trim();if(dialogAction==='delete'&&activeId!==busyId){sessions=sessions.filter(s=>s.id!==activeId);activeId='draft';initExpansion();}renderShell();});
$('#draft').addEventListener('input',ev=>drafts[activeId]=ev.target.value);
$('#composer').addEventListener('submit',ev=>{ev.preventDefault();const text=$('#draft').value.trim();if(!text||busyId)return;if(!current()){const id=`session-${++serial}`;sessions.unshift({id,title:text.slice(0,22),time:'刚刚 · 模拟保存',turns:[]});activeId=id;}const t=makeTurn(text,'running');const previous=current().turns.filter(x=>x.mode!=='interrupted').flatMap(x=>[{role:'user',content:x.input},{role:'assistant',content:x.answer}]);t.requests[0].input.messages=[...previous,{role:'user',content:text}];current().turns.push(t);drafts[activeId]='';drafts.draft='';busyId=activeId;stopping=false;openTurns.add(t.id);openRequests.add(t.requests[0].id);renderShell();$('#messages').scrollTop=$('#messages').scrollHeight;});
$('#draft').addEventListener('keydown',ev=>{if(ev.key==='Enter'&&!ev.shiftKey&&!ev.isComposing){ev.preventDefault();$('#composer').requestSubmit();}});
$('#search').addEventListener('input',ev=>{query=ev.target.value;renderTrace();});$('#scope').addEventListener('change',ev=>{scope=ev.target.value;renderTrace();});
$('#follow').addEventListener('change',()=>{if($('#follow').checked&&hasNew){hasNew=false;selectEvent(current().turns.at(-1).events.at(-1).id);}});
document.addEventListener('keydown',ev=>{if(ev.target.matches('input,textarea,select,[contenteditable]')||$('#manage').open)return;if(ev.key==='ArrowLeft'||ev.key==='ArrowRight'){ev.preventDefault();switchVariant(ev.key==='ArrowRight'?1:-1);}if(ev.key==='Escape'&&selection){selection=null;renderTrace();}});
renderShell();
